language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install pycodestyle pyflakes
  - pip install .
script:
  - pyflakes .
  - pycodestyle --ignore E203 --max-line-length 88 .
  - python setup.py check --metadata --strict
  - python setup.py pytest --verbose
