language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install flake8
  - pip install .
script:
  - kitten --version
  - flake8 --ignore E203,E501
  - python setup.py check --metadata --strict
